// Copyright 2026 QMK -- generated source code only, image retains original copyright
// SPDX-License-Identifier: GPL-2.0-or-later

// This file was auto-generated by `painter_convert_graphics` with arguments:
//    format | rgb888
//    output | Downloads
//    input  | cyberpunk_tft_scaled.png

#pragma once

#include <qp.h>

extern const uint32_t gfx_cyberpunk_tft_scaled_length;
extern const uint8_t  gfx_cyberpunk_tft_scaled[97248];
